routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/pnv', function () {
//    $arr = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"];
//    return view('pnv', ['planet'=>$arr]);
//});
//Route::get('/adminshow', function () {
//    return view('adminshow');
//});
//
//Route::get('/admin', function () {
//    return view('admin.post.index');
//});
/////////////////////////////////////////////
//Route::get('/pnv',"PNVController@showPnv");
//Route::post('/pnv',"PNVController@processLogin");
//
//Route::get('/admin/user',"ExController@showUserIndex");
//Route::post('/admin/user/create',"ExController@createUser");
//****************************************************//
// Old version without Middleware
//****************************************************//
//Route::resource('admin/users',"AdminUsersController", array('as'=>'admin'));
//Auth::routes();
//
//Route::resource('admin/categories',"AdminCategoriesController", array('as'=>'admin'));
//Auth::routes();
//
//Route::resource('admin/posts',"AdminPostsController", array('as'=>'admin'));
//Auth::routes();
//
//Route::resource('admin/media',"AdminMediaController", array('as'=>'admin'));
//Auth::routes();
//
//Route::get('admin/posts/showByAuthor/{id}', 'AdminPostsController@showByAuthor')->name('admin.posts.showByAuthor');
//Auth::routes();
//****************************************************//
// New version within Middleware
//****************************************************//
Route::group(['middleware' => 'admin'], function() {
    Route::resource('admin/users', "AdminUsersController", array('as' => 'admin'));

    Route::resource('admin/categories', "AdminCategoriesController", array('as' => 'admin'));

    Route::resource('admin/posts', "AdminPostsController", array('as' => 'admin'));

    Route::resource('admin/media', "AdminMediaController", array('as' => 'admin'));

    Route::get('admin/posts/showByAuthor/{id}', 'AdminPostsController@showByAuthor')->name('admin.posts.showByAuthor');
});

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home/category/{id}', 'HomeController@showByCategory')->name('home.showByCategory');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/post/{id}', ['as' => 'home.post', 'uses' => 'HomeController@post']);

Route::resource('/posts', "UserPostController", array('as' => 'user'));
Auth::routes();

Route::post('/posts/addComment/{id}', "UserPostController@addComment")->name('user.posts.addComment');
Auth::routes();

Route::post('/posts/addChildComment/{post_id}/{parent_id}', "UserPostController@addChildComment")->name('user.posts.addChildComment');
Auth::routes();

//Route::post('/user/search/{text}',"UserPostController@search")->name('user.search');
//Auth::routes();

Route::get('/user/search', "UserPostController@search")->name('user.search');
Auth::routes();

resources/views/admin/media/index.blade.php
<?php

use Carbon\Carbon;
?>

@extends ('layout.admin')

@section('content')
<h1>All Media</h1>
<div class="box-content">
    @if (Session::has('notification'))
    <div class="alert alert-success" id="notify">
        <button data-dismiss="alert" class="close">×</button>
        {{ Session::get('notification') }}
    </div>
    @endif
    <h2>Thumbnail</h2>
    @if(count($media) > 0)
    <div class="row">
        @foreach($media AS $key => $value)
        @if(File::exists(public_path($value->photo)))
        <form id="photo_{{$value->photo_id}}" action="{{ route('admin.media.destroy', $value->photo_id)}}" method="POST" class="media-box">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
            <img src="{{$value->photo?asset($value->photo):'http://placehold.it/400x300'}}" width="300px" alt="" class="img-responsive img-round">
            <h4 id="name_{{$value->photo_id}}">{{$value->post_name}}</h4>
            <!--<input type="submit" name="submit" class="btn btn-danger" value="Delete">-->

            <button type="button" name="buttonZ" class="btn btn-danger delete-fnt"
                    data-type="photo" data-id="{{ $value->photo_id }}" >
                Delete
            </button>
        </form>
        @endif
        @endforeach
        <div class="col-lg-6 col-sm-offset-5">
            {{ $media->render() }}
        </div>
    </div>
    @else
    <p>No Thumbnail</p>
    @endif
</div>
<div class="box-content">
    <h2>Extra Media</h2>
    @if(count($mediafull) > 0)
    <div class="row">
        @foreach($mediafull AS $key => $value)
        @if(File::exists(public_path($value->photo)))
        <form id="photo_{{$value->photo_id}}" action="{{ route('admin.media.destroy', $value->photo_id)}}" method="POST" class="media-box">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
            <img src="{{$value->photo?asset($value->photo):'http://placehold.it/400x300'}}" width="300px" alt="" class="img-responsive img-round">
            <h4 id="name_{{$value->photo_id}}">{{$value->post_name}}</h4>
            <!--<input type="submit" name="submit" class="btn btn-danger" value="Delete">-->

            <button type="button" name="buttonZ" class="btn btn-danger delete-fnt"
                    data-type="photo" data-id="{{ $value->photo_id }}">
                Delete
            </button>
        </form>
        @endif
        @endforeach
        <div class="col-lg-6 col-sm-offset-5">
            {{ $mediafull->render() }}
        </div>
    </div>
    @else
    <p>No Extra Media</p>
    @endif
</div>
@endsection