routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/pnv', function () {
//    $arr = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"];
//    return view('pnv', ['planet'=>$arr]);
//});
//Route::get('/adminshow', function () {
//    return view('adminshow');
//});
//
//Route::get('/admin', function () {
//    return view('admin.post.index');
//});
/////////////////////////////////////////////
//Route::get('/pnv',"PNVController@showPnv");
//Route::post('/pnv',"PNVController@processLogin");
//
//Route::get('/admin/user',"ExController@showUserIndex");
//Route::post('/admin/user/create',"ExController@createUser");
//****************************************************//
// Old version without Middleware
//****************************************************//
//Route::resource('admin/users',"AdminUsersController", array('as'=>'admin'));
//Auth::routes();
//
//Route::resource('admin/categories',"AdminCategoriesController", array('as'=>'admin'));
//Auth::routes();
//
//Route::resource('admin/posts',"AdminPostsController", array('as'=>'admin'));
//Auth::routes();
//
//Route::resource('admin/media',"AdminMediaController", array('as'=>'admin'));
//Auth::routes();
//
//Route::get('admin/posts/showByAuthor/{id}', 'AdminPostsController@showByAuthor')->name('admin.posts.showByAuthor');
//Auth::routes();
//****************************************************//
// New version within Middleware
//****************************************************//
Route::group(['middleware' => 'admin'], function() {
    Route::resource('admin/users', "AdminUsersController", array('as' => 'admin'));

    Route::resource('admin/categories', "AdminCategoriesController", array('as' => 'admin'));

    Route::resource('admin/posts', "AdminPostsController", array('as' => 'admin'));

    Route::resource('admin/media', "AdminMediaController", array('as' => 'admin'));

    Route::get('admin/posts/showByAuthor/{id}', 'AdminPostsController@showByAuthor')->name('admin.posts.showByAuthor');
});

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home/category/{id}', 'HomeController@showByCategory')->name('home.showByCategory');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/post/{id}', ['as' => 'home.post', 'uses' => 'HomeController@post']);

Route::resource('/posts', "UserPostController", array('as' => 'user'));
Auth::routes();

Route::post('/posts/addComment/{id}', "UserPostController@addComment")->name('user.posts.addComment');
Auth::routes();

Route::post('/posts/addChildComment/{post_id}/{parent_id}', "UserPostController@addChildComment")->name('user.posts.addChildComment');
Auth::routes();

//Route::post('/user/search/{text}',"UserPostController@search")->name('user.search');
//Auth::routes();

Route::get('/user/search', "UserPostController@search")->name('user.search');
Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id', 'is_active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
    public function is_Admin(){
        if($this->role()->name == 'Admin') {
            return TRUE;
        }
        return FALSE;
    }


    public function role()
    {
        return $this->belongsTo('App\Role')->first();
    }
    
    public function photos() {
        return $this->hasMany('App\Photo');
    }
    
    public function avatar() {
        return $this->photos()->where('is_thumbnail','=', 1)->first();
    }
}

resources/views/admin/users/create.blade.php
@extends ('layout.admin');
@section ('content')

<h1 style="text-align: center; color: #123489;">
    Create User
</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form action="{{ route('admin.users.store') }}" method="POST" enctype='multipart/form-data'>
            <input type="hidden" name="_token" value="{{ csrf_token() }}">

            <div class=" row  form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                <label for="email">Email:</label>
                <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email" value="{{ old('email') }}">
                <span class="text-danger">{{ $errors->first('email') }}</span>
            </div>


            <div class=" row form-group {{ $errors->has('username') ? 'has-error' : '' }}">
                <label for="name">Full name:</label>
                <input type="text" id="username" name="name" class="form-control" placeholder="Enter full name" value="{{ old('name') }}">
                <span class="text-danger">{{ $errors->first('name') }}</span>
            </div>        

            <div class=" row form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" class="form-control" value="{{ old('password') }}">
                <span class="text-danger">{{ $errors->first('password') }}</span>
            </div>

            <div class=" row form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                <label for="password">Re-Password:</label>
                <input type="password" id="repassword" name="repassword" class="form-control" value="{{ old('repassword') }}">
                <span class="text-danger">{{ $errors->first('repassword') }}</span>
            </div>

            <div class=" row form-group">
                <label for="role">Role: </label>
                <select id="role_id" name="role_id" class="form-control">
                    @foreach ($roles AS $role)
                    <option value="{{ $role->id }}" {{ $role->name=='User'?'selected':'' }} >
                        {{ $role->name }}
                    </option>
                    @endforeach
                </select>
            </div>

            <div class=" row form-group">
                <label for="role">Active: </label>
                <select id="is_active" name="is_active" class="form-control">
                    <option value="0">No</option>
                    <option value="1" selected="true">Yes</option>
                </select>
            </div>

            <div class=" row form-group {{ $errors->has('avatar') ? 'has-error' : '' }}">
                <label for="avatar">Avatar: </label>
                <input type="file" id="avatar" name="avatar" class="form-control" value="{{ old('avatar') }}">
                <span class="text-danger">{{ $errors->first('avatar') }}</span>
            </div> 

            <div class="form-group">
                <input type="submit" name="submit" class="btn btn-success" value="submit" />
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends ('layout.admin');
@section ('content')

<h1 style="text-align: center; color: #123489;">
    Edit User
</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-2">
        <form action="{{ route('admin.users.update', $user->id) }}" method="POST" enctype='multipart/form-data'>
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="_method" value="PUT">

            <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                <label for="email">Email:</label>
                <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email" 
                       value="<?php if (old('email') != '') echo old('email');
else echo $user['email'] ?>" disabled>
                <span class="text-danger">{{ $errors->first('email') }}</span>
            </div>


            <div class="form-group {{ $errors->has('username') ? 'has-error' : '' }}">
                <label for="name">Username:</label>
                <input type="text" id="username" name="name" class="form-control" placeholder="Enter user name" 
                       value="<?php if (isset($user)) echo $user['name'];
else echo old('name') ?>">
                <span class="text-danger">{{ $errors->first('name') }}</span>
            </div>        

            <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" class="form-control" value="{{ old('password') }}">
                <span class="text-danger">{{ $errors->first('password') }}</span>
            </div> 

            <div class="form-group" style="">
                <img width="400px" class="img-responsive img-display"
                     src="<?php
                     if ($user->avatar()) {
                         if (File::exists(public_path($user->avatar()->path)))
                             echo asset($user->avatar()->path);
                         else
                             echo 'http://placehold.it/1200x800';
                     } else {
                         echo 'http://placehold.it/1200x800';
                     }
                     ?>"
                     >
            </div> <br>

            <div class="form-group {{ $errors->has('avatar') ? 'has-error' : '' }}">
                <label for="avatar">Avatar: </label>
                <input type="file" id="avatar" name="avatar" class="form-control" value="{{ old('avatar') }}">
                <span class="text-danger">{{ $errors->first('avatar') }}</span>
            </div>
            
            @if($user->id !=1)
            <div class=" form-group {{ $errors->has('role') ? 'has-error' : '' }}">
                <label for="role">Role:</label>
                <select id="role" name="role_id" class="form-control">
                    @foreach ($roles AS $key => $role)
                    <option value="{{ $role->id }}" {{($role->id == $user->role_id)?'selected':''}}> {{ $role->name }} </option>
                    @endforeach
                </select>
            </div>
            @endif

            <div class=" form-group {{ $errors->has('is_active') ? 'has-error' : '' }}">
                <label for="category_id">Is active account:</label>
                <input type="checkbox" id="is_active" name="is_active" value="1" @if ( $user->is_active == 1 ) checked   @endif />
                       <span class="text-danger">{{ $errors->first('is_active') }}</span>
            </div>

            <div class="form-group">
                <input type="submit" name="submit" class="btn btn-success" value="submit" />
            </div>
            <?php
            unset($user);
            ?>
        </form>
    </div>
</div>

@endsection

resources/views/admin/users/edit2.blade.php
@extends('layout.admin')




@section('content')


<h1>Edit Users</h1>

<div class="row">

    <form action="{{ route('admin.users.update', $user->id) }}" method="POST" >
        <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
        <input type="hidden" name="_method" value="PUT">


        <div class=" form-group {{ $errors->has('name') ? 'has-error' : '' }}">
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" class="form-control" placeholder="Enter name" value="{{ $user->name  }}">
            <span class="text-danger">{{ $errors->first('name') }}</span>
        </div>   

        <div class="  form-group {{ $errors->has('email') ? 'has-error' : '' }}">
            <label for="email">Email:</label>
            <input type="text" disabled="" id="email" name="email" class="form-control" placeholder="Enter Email" value="{{ $user->email  }}">
            <span class="text-danger">{{ $errors->first('email') }}</span>
        </div>

        <!--            <div class=" form-group {{ $errors->has('is_active') ? 'has-error' : '' }}">
                            <label for="category_id">Is active account:</label>
                            <input type="checkbox" id="is_active" name="is_active" value="1" @if ( $user->is_active == 1 ) checked   @endif />
                                          
                            <span class="text-danger">{{ $errors->first('is_active') }}</span>
                    </div>  -->

        <div class="  form-group {{ $errors->has('password') ? 'has-error' : '' }}">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" class="form-control" value="">
            <span class="text-danger">{{ $errors->first('password') }}</span>
        </div> 


        <div class="form-group">
            <input type="submit" class="btn btn-success" value="Edit User" />
        </div>
    </form>

    <form action="{{ route('admin.users.destroy', $user->id) }}" method="POST" >
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
        <div class="form-group">
            <input type="submit" class="btn btn-danger" value="Delete User" />

        </div>
    </form>

</div>    
@stop

resources/views/admin/users/index.blade.php
<?php

use Carbon\Carbon;
use Illuminate\Support\Facades\File;
?>

@extends ('layout.admin')

@section('content')
<h1>Users</h1>
@if (Session::has('notification'))
<div class="alert alert-success" id="notify">
    <button data-dismiss="alert" class="close">×</button>
    {!! Session::get('notification') !!}
</div>
@endif

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Avatar</th>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Status</th>
            <th>Created Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>

        @if(count($users) > 0)
        @foreach ($users AS $key => $user)
        <tr>
            <td>{{ $user->id }}</td>
            <td>
                <img height="50" 
                     src="<?php
                     if ($user->avatar()) {
                         if (File::exists(public_path($user->avatar()->path)))
                             echo asset($user->avatar()->path);
                         else
                             echo 'http://placehold.it/1200x800';
                     } else {
                         echo 'http://placehold.it/1200x800';
                     }
                     ?>"
                     >
            </td>
            <td><a href="{{route('admin.users.edit', $user->id)}}">{{ $user->name }}</a></td>
            <td>{{ $user->email }}</td>
            <td>{{ $user->role() ? $user->role()->name:'Another' }}</td>
            <td>{{ $user->is_active==1?'Actived':'No Actived' }}</td>
            <td>{{ $user->created_at }}</td>
            <td>
                <a class="button-a edit-button" href="{{route('admin.users.edit', $user->id)}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>&nbsp;
<!--                @if($user->id !=1)
                <form action="{{route('admin.users.destroy', $user->id)}}" method="POST" class="form-delete"> 
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                    <button type="submit" name="submit" class="button-space button-a delete-button">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </button>
                </form>
                @endif-->
            </td>
        </tr>
        @endforeach
        @else 
        <tr><td> No User </td></tr>;
        @endif
    </tbody>
</table>

<div class="row">
    <div class="col-lg-6 col-sm-offset-5">
        {{ $users->render() }}
    </div>

</div>

@endsection