routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/pnv', function () {
//    $arr = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"];
//    return view('pnv', ['planet'=>$arr]);
//});
//Route::get('/adminshow', function () {
//    return view('adminshow');
//});
//
//Route::get('/admin', function () {
//    return view('admin.post.index');
//});
/////////////////////////////////////////////
//Route::get('/pnv',"PNVController@showPnv");
//Route::post('/pnv',"PNVController@processLogin");
//
//Route::get('/admin/user',"ExController@showUserIndex");
//Route::post('/admin/user/create',"ExController@createUser");
//****************************************************//
// Old version without Middleware
//****************************************************//
//Route::resource('admin/users',"AdminUsersController", array('as'=>'admin'));
//Auth::routes();
//
//Route::resource('admin/categories',"AdminCategoriesController", array('as'=>'admin'));
//Auth::routes();
//
//Route::resource('admin/posts',"AdminPostsController", array('as'=>'admin'));
//Auth::routes();
//
//Route::resource('admin/media',"AdminMediaController", array('as'=>'admin'));
//Auth::routes();
//
//Route::get('admin/posts/showByAuthor/{id}', 'AdminPostsController@showByAuthor')->name('admin.posts.showByAuthor');
//Auth::routes();
//****************************************************//
// New version within Middleware
//****************************************************//
Route::group(['middleware' => 'admin'], function() {
    Route::resource('admin/users', "AdminUsersController", array('as' => 'admin'));

    Route::resource('admin/categories', "AdminCategoriesController", array('as' => 'admin'));

    Route::resource('admin/posts', "AdminPostsController", array('as' => 'admin'));

    Route::resource('admin/media', "AdminMediaController", array('as' => 'admin'));

    Route::get('admin/posts/showByAuthor/{id}', 'AdminPostsController@showByAuthor')->name('admin.posts.showByAuthor');
});

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home/category/{id}', 'HomeController@showByCategory')->name('home.showByCategory');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/post/{id}', ['as' => 'home.post', 'uses' => 'HomeController@post']);

Route::resource('/posts', "UserPostController", array('as' => 'user'));
Auth::routes();

Route::post('/posts/addComment/{id}', "UserPostController@addComment")->name('user.posts.addComment');
Auth::routes();

Route::post('/posts/addChildComment/{post_id}/{parent_id}', "UserPostController@addChildComment")->name('user.posts.addChildComment');
Auth::routes();

//Route::post('/user/search/{text}',"UserPostController@search")->name('user.search');
//Auth::routes();

Route::get('/user/search', "UserPostController@search")->name('user.search');
Auth::routes();

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model {

    use FullTextSearch;

    protected $fillable = [
        'user_id', 'category_id', 'title', 'body'
    ];

    /**
     * The columns of the full text index
     */
    protected $searchable = [
        'title',
        'body',
    ];

    public function photos() {
        return $this->hasMany('App\Photo');
    }

    public function photo_thumbnail() {
//        return $this->hasMany('App\Photo')->wherePivot('is_thumbnail', 1);
//        $instance->where([['post_id', '=', $post_id],['is_thumbnail', '=', 1]]);
//        return $instance;
        return $this->photos()->where('is_thumbnail','=', 1)->first();
    }

}

resources/views/admin/posts/create.blade.php
@extends('layout.admin')

@section('content')
@include('includes.tinyeditor')

<h1>Create Post</h1>

<div class="row">

    <form action="{{ route('admin.posts.store') }}" method="POST" enctype='multipart/form-data'>
        <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
        
        <div class=" form-group {{ $errors->has('title') ? 'has-error' : '' }}">
            <label for="title">Title:</label>
            <input type="text" id="title" name="title" class="form-control" placeholder="Enter title" value="{{ old('title') }}">
            <span class="text-danger">{{ $errors->first('title') }}</span>
        </div>        
        <div class=" form-group {{ $errors->has('category_id') ? 'has-error' : '' }}">
            <label for="category_id">Category:</label>
            <select class="form-control" id="category_id" name="category_id" >
                @foreach ($categories as $id => $name  )
                <option value="{{$id}}">{{$name}}</option>
                @endforeach   
            </select>                
            <span class="text-danger">{{ $errors->first('category_id') }}</span>
        </div>  


        <div class="  form-group {{ $errors->has('photo_id') ? 'has-error' : '' }}">
            <label for="photo_id">Thumnail:</label>
            <input type="file" id="photo_id" name="photo_id" class="form-control" value="{{ old('photo_id') }}">
            <span class="text-danger">{{ $errors->first('photo_id') }}</span>
        </div> 


        <div class=" form-group {{ $errors->has('body') ? 'has-error' : '' }}">
            <label for="body">Title:</label>
            <textarea class="form-control" rows="5" id="body" name="body">{{ old('body') }}</textarea>
            <span class="text-danger">{{ $errors->first('body') }}</span>
        </div> 

        <div class="form-group">
            <input type="submit" class="btn btn-success" value="Create Post" />
        </div>
    </form>
</div>


<div class="row">
    @include('includes.form_error')
</div>
@stop

resources/views/admin/posts/edit.blade.php
@extends('layout.admin')

@section('content')
@include('includes.tinyeditor')

<h1>Create Post</h1>

<div class="row">

    <form action="{{ route('admin.posts.update', $post->id) }}" method="POST" enctype='multipart/form-data'>
        <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
        <input type="hidden" name="_method" value="PUT">


        <div class=" form-group {{ $errors->has('title') ? 'has-error' : '' }}">
            <label for="title">Title:</label>
            <input type="text" id="title" name="title" class="form-control" placeholder="Enter title" value="{{ old('title')?old('title'):$post->title }}">
            <span class="text-danger">{{ $errors->first('title') }}</span>
        </div>        
        <div class=" form-group {{ $errors->has('category_id') ? 'has-error' : '' }}">
            <label for="category_id">Category:</label>
            <select class="form-control" id="category_id" name="category_id" >
                @foreach ($categories as $id => $name  )
                <option value="{{$id}}"   {{ $id == $post->category_id ? 'selected="selected"' : '' }}
                    >
                    {{$name}}
                </option>
                @endforeach   
            </select>                
            <span class="text-danger">{{ $errors->first('category_id') }}</span>
        </div>  
        <div class="form-group " style="">
            <img src="{{File::exists(public_path($post->photo))?asset($post->photo):'http://placehold.it/1200x800'}}" width="400px" alt="" class="img-responsive img-rounded img-display">
        </div> <br>

        <div class="  form-group {{ $errors->has('photo_id') ? 'has-error' : '' }}">
            <label for="photo_id">Thumnail:</label>
            <input type="file" id="photo_id" name="photo_id" class="form-control" value="{{ old('photo_id') }}">
            <span class="text-danger">{{ $errors->first('photo_id') }}</span>
        </div> 


        <div class=" form-group {{ $errors->has('body') ? 'has-error' : '' }}">
            <label for="body">Content:</label>
            <textarea class="form-control" rows="5" id="body" name="body">{{ old('body')?old('body'):$post->body }}</textarea>
            <span class="text-danger">{{ $errors->first('body') }}</span>
        </div> 

        <div class="form-group">
            <input type="submit" class="btn btn-success" value="Update Post" />
        </div>
    </form>

    <form id="post_{{$post->id}}" action="{{ route('admin.posts.destroy', $post->id)}}" method="POST">
        <div class="form-group">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
            <p id="name_{{$post->id}}" style="display: none">{{$post->title}}</p>
            <!--<input type="submit" name="delete_submit" class="btn btn-danger" value="Delete Post">-->
            <button type="button" name="buttonZ" class="button-space button-a delete-button delete-fnt"
                    data-type="post" data-id="{{ $post->id }}">
                <i class="fa fa-trash-o" aria-hidden="true"></i>
            </button>
        </div>
    </form>
</div>


<div class="row">


    @include('includes.form_error')



</div>




@stop

resources/views/admin/posts/index.blade.php
<?php

use Carbon\Carbon;
use Illuminate\Support\Facades\File;
?>

@extends ('layout.admin')

@section('content')
<h1>Posts</h1>
@if (Session::has('notification'))
<div class="alert alert-success" id="notify">
    <button data-dismiss="alert" class="close">×</button>
    {!! Session::get('notification') !!}
</div>
@endif

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Photo</th>
            <th>Owner</th>
            <th>Category</th>
            <th>Title</th>
            <th>Content</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th style="width: 20%">Action</th>
        </tr>
    </thead>
    <tbody>
        @if(count($posts) > 0)
        @foreach($posts as $post)

        <tr>
            <td>{{$post->id}}</td>
            <td>
                <img height="50" 
                     src="{{ File::exists(public_path($post->photo))?asset($post->photo):'http://placehold.it/1200x800' }}" alt="">
            </td>
            <td><a href="{{ route('admin.posts.showByAuthor', $post->user_id) }}">{{ $post->owner }}</a></td>
            <td>{{ $post->category }}</td>
            <td><a href="{{ url('admin/posts/'. $post->id.'/edit') }}" id="name_{{$post->id}}">{{$post->title}}</a></td>
            <td>{{str_limit(strip_tags($post->body), 30)}}</td>
            <td>{{Carbon::parse($post->created_at)->diffForHumans()}}</td>
            <td>{{Carbon::parse($post->updated_at)->diffForHumans()}}</td>
            <td>
                <a class="button-a view-button" href="{{route('home.post', $post->id)}}"><i class="fa fa-eye" aria-hidden="true"></i></a>&nbsp;
                <a class="button-a edit-button" href="{{route('admin.posts.edit', $post->id)}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>&nbsp;
                <a class="button-a view-cmt-button" href="{{route('admin.posts.show', $post->id)}}"><i class="fa fa-comments-o" aria-hidden="true"></i></a>&nbsp;
                <form id="post_{{ $post->id }}" action="{{route('admin.posts.destroy', $post->id)}}" method="POST" class="form-delete"> 
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                    <!--                    <button type="button" name="buttonZ" class="button-space button-a delete-button delete-fnt"
                                                onclick="confirmBeforeDelete({{ $post->id }}, 'post')">
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </button>-->

                    <button type="button" name="buttonZ" class="button-space button-a delete-button delete-fnt"
                            data-type="post" data-id="{{ $post->id }}">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </button>
                </form>

                <!--                <button type="button" name="submit" data-post-id="{{ $post->id }}" class="button-space button-a delete-button"
                                        onclick="confirmBeforeDelete(1, 'a')">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </button>-->
            </td>
        </tr>

        @endforeach

        @else 
        <tr>
            <td>No Posts</td>
        </tr>
        @endif

    </tbody>
</table>


<div class="row">
    <div class="col-lg-6 col-sm-offset-5">
        {{ $posts->render() }}
    </div>

</div>

@endsection

resources/views/admin/posts/show_by_author.blade.php
<?php

use Carbon\Carbon;
use Illuminate\Support\Facades\File;

$author = '';
?>

@extends ('layout.admin')

@section('content')
<?php
foreach ($posts as $post)
    $author = $post->owner;
?>
<h3> All posts of <?php echo $author ?></h3>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Photo</th>
            <th>Owner</th>
            <th>Category</th>
            <th>Title</th>
            <th>Content</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th style="width: 20%">Action</th>
        </tr>
    </thead>
    <tbody>
        @if(count($posts) > 0)
        @foreach($posts as $post)

        <tr>
            <td>{{$post->id}}</td>
            <td>
                <img height="50" 
                     src="{{ File::exists(public_path($post->photo))?asset($post->photo):'http://placehold.it/400x300' }}" alt="">
            </td>
            <td>{{ $post->owner }}</td>
            <td>{{ $post->category }}</td>
            <td><a id="name_{{$post->id}}" href="{{ url('admin/posts/'. $post->id.'/edit') }}">{{$post->title}}</a></td>
            <td>{{str_limit(strip_tags($post->body), 30)}}</td>
            <td>{{Carbon::parse($post->created_at)->diffForHumans()}}</td>
            <td>{{Carbon::parse($post->updated_at)->diffForHumans()}}</td>
            <td>
                <a class="button-a edit-button" href="{{route('admin.posts.edit', $post->id)}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>&nbsp;
                <a class="button-a edit-button" href="{{route('admin.posts.edit', $post->id)}}"><i class="fa fa-comments-o" aria-hidden="true"></i></a>&nbsp;
                <form id="post_{{ $post->id }}" action="{{route('admin.posts.destroy', $post->id)}}" method="POST" class="form-delete"> 
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                    <!--                    <button type="submit" name="submit" class="button-space button-a delete-button">
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </button>-->
                    <button type="button" name="buttonZ" class="button-space button-a delete-button delete-fnt"
                            data-type="post" data-id="{{ $post->id }}">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </button>
                </form>
            </td>
        </tr>

        @endforeach

        @else 
        <tr>
            <td>No Posts</td>
        </tr>
        @endif

    </tbody>
</table>


<div class="row">
    <div class="col-lg-6 col-sm-offset-5">
        {{ $posts->render() }}
    </div>

</div>
@endsection