routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/pnv', function () {
//    $arr = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"];
//    return view('pnv', ['planet'=>$arr]);
//});
//Route::get('/adminshow', function () {
//    return view('adminshow');
//});
//
//Route::get('/admin', function () {
//    return view('admin.post.index');
//});
/////////////////////////////////////////////
//Route::get('/pnv',"PNVController@showPnv");
//Route::post('/pnv',"PNVController@processLogin");
//
//Route::get('/admin/user',"ExController@showUserIndex");
//Route::post('/admin/user/create',"ExController@createUser");
//****************************************************//
// Old version without Middleware
//****************************************************//
//Route::resource('admin/users',"AdminUsersController", array('as'=>'admin'));
//Auth::routes();
//
//Route::resource('admin/categories',"AdminCategoriesController", array('as'=>'admin'));
//Auth::routes();
//
//Route::resource('admin/posts',"AdminPostsController", array('as'=>'admin'));
//Auth::routes();
//
//Route::resource('admin/media',"AdminMediaController", array('as'=>'admin'));
//Auth::routes();
//
//Route::get('admin/posts/showByAuthor/{id}', 'AdminPostsController@showByAuthor')->name('admin.posts.showByAuthor');
//Auth::routes();
//****************************************************//
// New version within Middleware
//****************************************************//
Route::group(['middleware' => 'admin'], function() {
    Route::resource('admin/users', "AdminUsersController", array('as' => 'admin'));

    Route::resource('admin/categories', "AdminCategoriesController", array('as' => 'admin'));

    Route::resource('admin/posts', "AdminPostsController", array('as' => 'admin'));

    Route::resource('admin/media', "AdminMediaController", array('as' => 'admin'));

    Route::get('admin/posts/showByAuthor/{id}', 'AdminPostsController@showByAuthor')->name('admin.posts.showByAuthor');
});

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home/category/{id}', 'HomeController@showByCategory')->name('home.showByCategory');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/post/{id}', ['as' => 'home.post', 'uses' => 'HomeController@post']);

Route::resource('/posts', "UserPostController", array('as' => 'user'));
Auth::routes();

Route::post('/posts/addComment/{id}', "UserPostController@addComment")->name('user.posts.addComment');
Auth::routes();

Route::post('/posts/addChildComment/{post_id}/{parent_id}', "UserPostController@addChildComment")->name('user.posts.addChildComment');
Auth::routes();

//Route::post('/user/search/{text}',"UserPostController@search")->name('user.search');
//Auth::routes();

Route::get('/user/search', "UserPostController@search")->name('user.search');
Auth::routes();

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name', 'created_at', 'updated_at'
    ];
}

resources/views/admin/categories/create.blade.php
@extends ('layout.admin');
@section ('content')

<h1 style="text-align: center; color: #123489;">
    Create Category
</h1>
<br><br>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form action="{{ route('admin.categories.store') }}" method="POST">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">

            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">Category Name:</label>
                <input type="text" id="name" name="name" class="form-control" placeholder="Enter Category Name" value="{{ old('name') }}">
                <span class="text-danger">{{ $errors->first('name') }}</span>
            </div>

            <div class="form-group">
                <input type="submit" name="submit" class="btn btn-success" value="submit" />
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends ('layout.admin');
@section ('content')

<h1 style="text-align: center; color: #123489;">
    Create Category
</h1>
<br><br>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form action="{{ route('admin.categories.update', $category->id) }}" method="POST">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="_method" value="PUT">

            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">Category Name:</label>
                <input type="text" id="name" name="name" class="form-control" placeholder="Enter Category Name"
                       value="{{ old('name')!=NULL?old('name'):$category->name }}">
                <span class="text-danger">{{ $errors->first('name') }}</span>
            </div>

            <div class="form-group">
                <input type="submit" name="submit" class="btn btn-success" value="submit" />
            </div>
        </form>

        <form id="category_{{$category->id}}" action="{{ route('admin.categories.destroy', $category->id) }}" method="POST">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
            <p id="name_{{$category->id}}" style="display: none">{{$category->name}}</p>
            <!--<input type="submit" name="delete_submit" class="btn btn-danger" value="Delete">-->
            <button type="button" name="buttonZ" class="button-space button-a delete-button delete-fnt"
                    data-type="category" data-id="{{ $category->id }}">
                <i class="fa fa-trash-o" aria-hidden="true"></i>
            </button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends ('layout.admin')

@section('content')
<h1>Categories</h1>
@if (Session::has('notification'))
<div class="alert alert-success" id="notify">
    <button data-dismiss="alert" class="close">×</button>
    {!! Session::get('notification') !!}
</div>
@endif

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Created Date</th>
            <th>Updated Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php
        if (count($categories) > 0) {
            ?>
            @foreach ($categories AS $category )
            <tr>
                <td>{{ $category->id }}</td>
                <td><a id="name_{{$category->id}}" href="{{route('admin.categories.edit', $category->id)}}">{{ $category->name }}</a></td>
                <td>{{ $category->created_at }}</td>
                <td>{{ $category->updated_at }}</td>
                <td>
                    <a class="button-a edit-button" href="{{route('admin.categories.edit', $category->id)}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>&nbsp;
                    <!--<a class="button-a delete-button" href="{{route('admin.categories.destroy', $category->id)}}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>-->
                    <form id="category_{{$category->id}}" action="{{route('admin.categories.destroy', $category->id)}}" method="POST" class="form-delete"> 
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                        <!--                        <button type="submit" name="submit" class="button-space button-a delete-button">
                                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                                </button>-->

                        <button type="button" name="buttonZ" class="button-space button-a delete-button delete-fnt"
                                data-type="category" data-id="{{ $category->id }}">
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                    </form>
                </td>
            </tr>
            @endforeach
            <?php
        } else {
            echo '<tr><td> No Category </td></tr>';
        }
        ?>
    </tbody>
</table>

<div class="row">
    <div class="col-lg-6 col-sm-offset-5">
        {{ $categories->render() }}
    </div>

</div>
@endsection